version: '3.8'

services:
  dbt:
    build:
      context: .  # The Dockerfile is in the current directory
      dockerfile: Dockerfile
    container_name: dbt-container
    volumes:
      - ./tpch_warehouse:/dbt  # Mount the tpch_warehouse folder to /dbt to container
    ports:
      - "8080:8080"  # Expose port 8080 on the host to port 8080 in the container
    command: tail -f /dev/null  # Keeps the container running